create_product:
  constraints:
    category_id: "required|uuid|exists:categories,id"
    code: "required|unique:products"
    name: "required|string"
    description: "string|nullable"
    stock: "required|integer"
    image: "required|string"
    status: "required|in:draft,published"

product_id:
  constraints:
    product: "required|uuid|exists:products,id"

edit_product:
  constraints:
    category_id: "uuid|exists:categories,id"
    code: "unique:products"
    name: "string"
    description: "string"
    stock: "integer"
    image: "string"
    status: "in:draft,published"